#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#   - Listens on port 80.
#   - Returns a page containing "Hello World!" when queried
#     at the root with a curl GET request.

apt-get update
apt-get install -y nginx

# Create directories and files
mkdir -p /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html

# Configure Nginx
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
    location / {
        try_files \$uri \$uri/ =404;
    }
}
" > /etc/nginx/sites-available/default

# Restart Nginx without using systemctl
service nginx restart
