#!/usr/bin/env bash
# Script to configure a new Ubuntu machine to match web-01 server

# Uncomment to see the script run in action
#set -x

echo -e "Updating and doing some minor checks...\n"

function install() {
    command -v "$1" &> /dev/null

    #shellcheck disable=SC2181
    if [ $? -ne 0 ]; then
        echo -e "Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "${1} is already installed.\n"
    fi
}

# Install Nginx
install nginx

echo -e "\nSetting up some minor stuff.\n"

# Allowing Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
if [ -d "/var/www" ]; then
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
else
    sudo mkdir -p /var/www
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
fi

# Create directories if not present
for dir in /var/www/{html,error}; do
    if ! [ -d "$dir" ]; then
        mkdir -p "$dir"
    fi
done

# Create new index
echo "Hello World!" > /var/www/html/index.html

# Create new error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Backup default server config file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

# Configuring Nginx to add custom header
sudo sed -i '/listen 80 default_server;/a \ \t add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Enabling the server configuration
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
