#!/bin/bash

# Update package lists
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Set hostname for web servers
sudo hostnamectl set-hostname 505234-web-01
echo "127.0.0.1 505234-web-01" | sudo tee -a /etc/hosts > /dev/null

sudo hostnamectl set-hostname 505234-web-02
echo "127.0.0.1 505234-web-02" | sudo tee -a /etc/hosts > /dev/null

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 505234-web-01:80 check
    server web-02 505234-web-02:80 check
EOF

# Enable HAProxy service
sudo systemctl enable haproxy

# Restart HAProxy to apply changes
sudo systemctl restart haproxy
